"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { Code, Award, ArrowRight } from "lucide-react";
import styles from "./Projects.module.css";

interface Project {
  title: string;
  category: string;
  description: string;
  /** What the project actually produced or resolved — not just the stack used. */
  outcome: string;
  tags: string[];
  image?: string;
  link?: string;
  certificateUrl?: string;
  caseStudyUrl?: string;
}

const projectData: Project[] = [
  {
    title: "PepeLab — Decentralized Credential Verification",
    category: "Award-winning Project (Merit Award)",
    description:
      "Led a team in a national competition hosted by the Ministry of Digital Affairs, Taiwan. Cross-agency credential verification in the public sector lacks interoperable infrastructure, forcing citizens to re-submit the same credentials to every institution. Architected a decentralized identity platform on SSI, VC, and DID standards to make those credentials verifiable across institutions.",
    outcome:
      "Merit Award (學生組優選) at the Digital Credential Scenario Innovation Challenge, Nov 2025. Delivered a working credential verification system and translated government interoperability requirements into implementable technical specifications.",
    tags: ["SSI", "VC/DID", "FastAPI", "Python", "System Architecture"],
    image: "/digital_credential_new.jpg",
    link: "https://github.com/zuemen/pepelab_v2",
    certificateUrl: "/awards/moda-digital-credential-2025-certificate.pdf",
    caseStudyUrl: "/projects/pepelab",
  },
  {
    title: "Real World Asset (RWA) Real Estate Tokenization",
    category: "Blockchain Implementation",
    description:
      "Developed a decentralized platform for real estate fractional ownership. Implemented PropertyToken for asset digitization and RentalDistributor for automated yield distribution. Integrated an IdentityRegistry to ensure regulatory compliance.",
    outcome:
      "A working end-to-end demo on a local Hardhat network: four Solidity contracts (IdentityRegistry, PropertyToken, RentalDistributor, MockUSDC) wired to a React frontend and a Node backend, so an identity-gated transfer and an automated rental payout can be run start to finish. Shows compliance constraints enforced in the contracts rather than bolted on off-chain.",
    tags: ["Solidity", "Hardhat", "RWA", "Fractional Ownership", "React"],
    link: "https://github.com/zuemen/rwa_g",
  },
  {
    title: "Quantum Machine Learning (QML) Simulation",
    category: "Quantum Research",
    description:
      "A controlled comparison of quantum and classical classifiers under a 2×2 design: two data sources (a classical non-linearly-separable set, and one generated by sampling a parameterised two-qubit circuit) crossed with two model families. Implemented on Qiskit Aer with QSVM (ZZFeatureMap + fidelity quantum kernel), a variational QNN, and a QSVT-style approximation, against a logistic-regression baseline.",
    // TODO(zuemen): the notebook ships without stored cell outputs, so no
    // accuracy figures can be cited here. Re-run it with outputs committed and
    // send me the results table from section 11 — a headline number, or a
    // negative result, would both strengthen this card considerably.
    outcome:
      "Isolates whether any advantage comes from the data or the model by testing both quantum and classical algorithms on both data sources — a cleaner comparison than benchmarking a quantum model on classical data alone.",
    tags: ["QML", "Qiskit", "QSVM", "QNN", "Python"],
    link: "https://github.com/zuemen/qc_ML",
  },
];

const Projects = () => {
  return (
    <section id="projects" className={styles.projects}>
      <div className={styles.container}>
        <motion.div
          className={styles.header}
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
        >
          <h2 className={styles.heading}>Research &amp; Projects</h2>
          <p className={styles.subtitle}>
            Bridging emerging technologies with institutional needs.
          </p>
        </motion.div>

        <div className={styles.list}>
          {projectData.map((project) => (
            <motion.div
              key={project.title}
              className={styles.projectItem}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              {project.image && (
                <div className={styles.projectImageWrapper}>
                  <Image
                    src={project.image}
                    alt={`Screenshot of ${project.title}`}
                    width={480}
                    height={270}
                    sizes="(max-width: 768px) 100vw, 480px"
                    className={styles.projectImage}
                    style={{ objectFit: "cover" }}
                  />
                </div>
              )}
              <div className={styles.projectInfo}>
                <span className={styles.category}>{project.category}</span>
                <h3 className={styles.title}>{project.title}</h3>
                <p className={styles.desc}>{project.description}</p>
                <div className={styles.outcome}>
                  <span className={styles.outcomeLabel}>Outcome</span>
                  <p className={styles.outcomeText}>{project.outcome}</p>
                </div>
                <div className={styles.tags}>
                  {project.tags.map((tag) => (
                    <span key={tag} className={styles.tag}>
                      {tag}
                    </span>
                  ))}
                </div>
                <div className={styles.links}>
                  {project.caseStudyUrl && (
                    <Link
                      href={project.caseStudyUrl}
                      className={styles.caseStudyLink}
                    >
                      Read case study <ArrowRight size={14} />
                    </Link>
                  )}
                  {project.link && (
                    <a
                      href={project.link}
                      className={styles.linkIcon}
                      target="_blank"
                      rel="noopener noreferrer"
                      aria-label={`View source code for ${project.title}`}
                    >
                      <Code size={20} />
                    </a>
                  )}
                  {project.certificateUrl && (
                    <a
                      href={project.certificateUrl}
                      className={styles.linkIcon}
                      target="_blank"
                      rel="noopener noreferrer"
                      aria-label="View Award Certificate (PDF)"
                    >
                      <Award size={20} />
                    </a>
                  )}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Projects;
