export interface Project {
  slug: string;
  title: string;
  /** Compact title for the homepage list, where the full one is too long. */
  shortTitle: string;
  category: string;
  /** One line for the homepage. The full description lives on /projects. */
  summary: string;
  description: string;
  /** What the project actually produced or resolved — not just the stack used. */
  outcome: string;
  tags: string[];
  image?: string;
  link?: string;
  certificateUrl?: string;
  caseStudyUrl?: string;
}

/**
 * Source of truth for projects, read by the Projects list on /projects and the
 * Selected Work section on the homepage, so the two cannot drift apart.
 */
export const projects: Project[] = [
  {
    slug: "pepelab",
    title: "PepeLab — Decentralized Credential Verification",
    shortTitle: "PepeLab",
    category: "Award-winning Project (Merit Award)",
    summary:
      "A decentralized identity platform on SSI, VC and DID standards, so a credential issued by one institution can be verified by another.",
    description:
      "Led a team in a national competition hosted by the Ministry of Digital Affairs, Taiwan. Cross-agency credential verification in the public sector lacks interoperable infrastructure, forcing citizens to re-submit the same credentials to every institution. Architected a decentralized identity platform on SSI, VC, and DID standards to make those credentials verifiable across institutions.",
    outcome:
      "Merit Award (學生組優選) at the Digital Credential Scenario Innovation Challenge, Nov 2025. Delivered a working credential verification system and translated government interoperability requirements into implementable technical specifications.",
    tags: ["SSI", "VC/DID", "FastAPI", "Python", "System Architecture"],
    image: "/digital_credential_new.jpg",
    link: "https://github.com/zuemen/pepelab_v2",
    certificateUrl: "/awards/moda-digital-credential-2025-certificate.pdf",
    caseStudyUrl: "/projects/pepelab",
  },
  {
    slug: "rwa-tokenization",
    title: "Real World Asset (RWA) Real Estate Tokenization",
    shortTitle: "RWA Real Estate Tokenization",
    category: "Blockchain Implementation",
    summary:
      "Fractional property ownership in Solidity, with compliance enforced inside the contracts rather than bolted on off-chain.",
    description:
      "Developed a decentralized platform for real estate fractional ownership. Implemented PropertyToken for asset digitization and RentalDistributor for automated yield distribution. Integrated an IdentityRegistry to ensure regulatory compliance.",
    outcome:
      "A working end-to-end demo on a local Hardhat network: four Solidity contracts (IdentityRegistry, PropertyToken, RentalDistributor, MockUSDC) wired to a React frontend and a Node backend, so an identity-gated transfer and an automated rental payout can be run start to finish. Shows compliance constraints enforced in the contracts rather than bolted on off-chain.",
    tags: ["Solidity", "Hardhat", "RWA", "Fractional Ownership", "React"],
    link: "https://github.com/zuemen/rwa_g",
  },
  {
    slug: "qml-simulation",
    title: "Quantum Machine Learning (QML) Simulation",
    shortTitle: "Quantum Machine Learning Simulation",
    category: "Quantum Research",
    summary:
      "A 2×2 benchmark crossing classical and quantum data sources with classical and quantum classifiers, to separate a data advantage from a model advantage.",
    description:
      "A controlled comparison of quantum and classical classifiers under a 2×2 design: two data sources (a classical non-linearly-separable set, and one generated by sampling a parameterised two-qubit circuit) crossed with two model families. Implemented on Qiskit Aer with QSVM (ZZFeatureMap + fidelity quantum kernel), a variational QNN, and a QSVT-style approximation, against a logistic-regression baseline.",
    // TODO(zuemen): the notebook ships without stored cell outputs, so no
    // accuracy figures can be cited here. Re-run it with outputs committed and
    // send me the results table from section 11 — a headline number, or a
    // negative result, would both strengthen this card considerably.
    outcome:
      "Isolates whether any advantage comes from the data or the model by testing both quantum and classical algorithms on both data sources — a cleaner comparison than benchmarking a quantum model on classical data alone.",
    tags: ["QML", "Qiskit", "QSVM", "QNN", "Python"],
    link: "https://github.com/zuemen/qc_ML",
  },
];
